//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Бипит_3.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillNaklodnie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FillNaklodnie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillNaklodnie", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> FillNaklodnieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillPostavshikt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FillPostavshikt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillPostavshikt", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> FillPostavshiktAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNaklodnie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertNaklodnie(string ID_POSTAVSHIK, string Cost_naklodnie, string Data_naklodnie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNaklodnie", ReplyAction="*")]
        System.Threading.Tasks.Task InsertNaklodnieAsync(string ID_POSTAVSHIK, string Cost_naklodnie, string Data_naklodnie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPostavshik", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertPostavshik(string Name_postavshik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPostavshik", ReplyAction="*")]
        System.Threading.Tasks.Task InsertPostavshikAsync(string Name_postavshik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Бипит_3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Бипит_3.ServiceReference1.WebService1Soap>, Бипит_3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable FillNaklodnie() {
            return base.Channel.FillNaklodnie();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> FillNaklodnieAsync() {
            return base.Channel.FillNaklodnieAsync();
        }
        
        public System.Data.DataTable FillPostavshikt() {
            return base.Channel.FillPostavshikt();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> FillPostavshiktAsync() {
            return base.Channel.FillPostavshiktAsync();
        }
        
        public void InsertNaklodnie(string ID_POSTAVSHIK, string Cost_naklodnie, string Data_naklodnie) {
            base.Channel.InsertNaklodnie(ID_POSTAVSHIK, Cost_naklodnie, Data_naklodnie);
        }
        
        public System.Threading.Tasks.Task InsertNaklodnieAsync(string ID_POSTAVSHIK, string Cost_naklodnie, string Data_naklodnie) {
            return base.Channel.InsertNaklodnieAsync(ID_POSTAVSHIK, Cost_naklodnie, Data_naklodnie);
        }
        
        public void InsertPostavshik(string Name_postavshik) {
            base.Channel.InsertPostavshik(Name_postavshik);
        }
        
        public System.Threading.Tasks.Task InsertPostavshikAsync(string Name_postavshik) {
            return base.Channel.InsertPostavshikAsync(Name_postavshik);
        }
    }
}
